# Generated by Django 3.2.6 on 2021-08-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'message': 'Usuário já cadastrado!', 'status': 'error'}, max_length=150, unique=True, verbose_name='username'),
        ),
    ]
