# Generated by Django 3.2.6 on 2021-08-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='search_position',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='user',
        ),
    ]
