# Generated by Django 3.2.6 on 2021-08-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210821_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='gender',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='bio',
            field=models.TextField(max_length=150),
        ),
    ]
