# Generated by Django 3.2.6 on 2021-08-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_userpreferences_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='birth',
            field=models.DateField(default=None),
        ),
    ]
