# Generated by Django 3.2.6 on 2021-08-22 17:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_userpreferences_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='user_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sup', 'Support'), ('mid', 'Mid'), ('adc', 'Adc'), ('top', 'Top'), ('jg', 'Jungle')], default=None, max_length=3),
        ),
    ]
