# Generated by Django 3.2.6 on 2021-08-22 18:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userpreferences_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='user_position',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'Mid'), ('top', 'Top'), ('adc', 'Atirador'), ('sup', 'Suporte'), ('jg', 'Caçador')], default=None, max_length=18),
        ),
    ]
