# Generated by Django 3.2.6 on 2021-08-22 21:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210822_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='USERNAME_FIELD',
            field=models.CharField(default=None, max_length=150, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'Caçador'), ('adc', 'Atirador'), ('top', 'Top'), ('mid', 'Mid'), ('sup', 'Suporte')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'Caçador'), ('adc', 'Atirador'), ('top', 'Top'), ('mid', 'Mid'), ('sup', 'Suporte')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'Caçador'), ('adc', 'Atirador'), ('top', 'Top'), ('mid', 'Mid'), ('sup', 'Suporte')], default=None, max_length=18),
        ),
    ]
