# Generated by Django 3.2.6 on 2021-08-22 21:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210822_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='puuid',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('top', 'Top'), ('mid', 'Mid'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('jg', 'Caçador')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('top', 'Top'), ('mid', 'Mid'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('jg', 'Caçador')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('top', 'Top'), ('mid', 'Mid'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('jg', 'Caçador')], default=None, max_length=18),
        ),
    ]
