# Generated by Django 3.2.6 on 2021-08-22 22:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210822_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puuid',
            field=models.CharField(max_length=200, null=True, verbose_name='puuid'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adc', 'Atirador'), ('sup', 'Suporte'), ('jg', 'Caçador'), ('top', 'Top'), ('mid', 'Mid')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adc', 'Atirador'), ('sup', 'Suporte'), ('jg', 'Caçador'), ('top', 'Top'), ('mid', 'Mid')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adc', 'Atirador'), ('sup', 'Suporte'), ('jg', 'Caçador'), ('top', 'Top'), ('mid', 'Mid')], default=None, max_length=18),
        ),
    ]
