# Generated by Django 3.2.6 on 2021-08-23 00:23

from django.conf import settings
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20210822_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='duo_refused',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'Caçador'), ('mid', 'Mid'), ('top', 'Top'), ('sup', 'Suporte'), ('adc', 'Atirador')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'Caçador'), ('mid', 'Mid'), ('top', 'Top'), ('sup', 'Suporte'), ('adc', 'Atirador')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('F', 'Feminino'), ('O', 'Outro'), ('M', 'Masculino')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'Caçador'), ('mid', 'Mid'), ('top', 'Top'), ('sup', 'Suporte'), ('adc', 'Atirador')], default=None, max_length=18),
        ),
    ]
