# Generated by Django 3.2.6 on 2021-08-23 11:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210822_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='duo_refused',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='duo_list',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'Caçador'), ('mid', 'Mid'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('top', 'Top')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'Caçador'), ('mid', 'Mid'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('top', 'Top')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'Caçador'), ('mid', 'Mid'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('top', 'Top')], default=None, max_length=18),
        ),
    ]
