# Generated by Django 3.2.6 on 2021-08-24 11:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20210823_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'Mid'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('jg', 'Caçador'), ('top', 'Top')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'Mid'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('jg', 'Caçador'), ('top', 'Top')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'Mid'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('jg', 'Caçador'), ('top', 'Top')], default=None, max_length=18),
        ),
    ]
