# Generated by Django 3.2.6 on 2021-08-24 19:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20210824_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sup', 'Suporte'), ('jg', 'Caçador'), ('mid', 'Mid'), ('adc', 'Atirador'), ('top', 'Top')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sup', 'Suporte'), ('jg', 'Caçador'), ('mid', 'Mid'), ('adc', 'Atirador'), ('top', 'Top')], default=None, max_length=18),
        ),
    ]
