# Generated by Django 3.2.6 on 2021-08-24 19:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20210824_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'Caçador'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('top', 'Top'), ('mid', 'Mid')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('O', 'Outro'), ('M', 'Masculino'), ('F', 'Feminino')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'Caçador'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('top', 'Top'), ('mid', 'Mid')], default=None, max_length=18),
        ),
    ]
