# Generated by Django 3.2.6 on 2021-08-25 00:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20210824_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='duo_match',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adc', 'Atirador'), ('top', 'Top'), ('mid', 'Mid'), ('sup', 'Suporte'), ('jg', 'Caçador')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adc', 'Atirador'), ('top', 'Top'), ('mid', 'Mid'), ('sup', 'Suporte'), ('jg', 'Caçador')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adc', 'Atirador'), ('top', 'Top'), ('mid', 'Mid'), ('sup', 'Suporte'), ('jg', 'Caçador')], default=None, max_length=18),
        ),
    ]
