# Generated by Django 3.2.6 on 2021-08-25 15:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20210824_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='match',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adc', 'Atirador'), ('jg', 'Caçador'), ('mid', 'Mid'), ('sup', 'Suporte'), ('top', 'Top')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adc', 'Atirador'), ('jg', 'Caçador'), ('mid', 'Mid'), ('sup', 'Suporte'), ('top', 'Top')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adc', 'Atirador'), ('jg', 'Caçador'), ('mid', 'Mid'), ('sup', 'Suporte'), ('top', 'Top')], default=None, max_length=18),
        ),
    ]
