# Generated by Django 3.2.6 on 2021-08-26 15:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20210825_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('top', 'Top'), ('adc', 'Atirador'), ('jg', 'Caçador'), ('sup', 'Suporte'), ('mid', 'Mid')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('top', 'Top'), ('adc', 'Atirador'), ('jg', 'Caçador'), ('sup', 'Suporte'), ('mid', 'Mid')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('F', 'Feminino'), ('O', 'Outro'), ('M', 'Masculino')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('top', 'Top'), ('adc', 'Atirador'), ('jg', 'Caçador'), ('sup', 'Suporte'), ('mid', 'Mid')], default=None, max_length=18),
        ),
    ]
