# Generated by Django 3.2.6 on 2021-08-27 19:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20210826_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'Mid'), ('jg', 'Caçador'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('top', 'Top')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'Mid'), ('jg', 'Caçador'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('top', 'Top')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('O', 'Outro'), ('F', 'Feminino'), ('M', 'Masculino')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'Mid'), ('jg', 'Caçador'), ('sup', 'Suporte'), ('adc', 'Atirador'), ('top', 'Top')], default=None, max_length=18),
        ),
    ]
