# Generated by Django 3.2.6 on 2021-08-28 23:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20210827_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'Mid'), ('top', 'Top'), ('adc', 'Atirador'), ('sup', 'Suporte'), ('jg', 'Caçador')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'Mid'), ('top', 'Top'), ('adc', 'Atirador'), ('sup', 'Suporte'), ('jg', 'Caçador')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'Mid'), ('top', 'Top'), ('adc', 'Atirador'), ('sup', 'Suporte'), ('jg', 'Caçador')], default=None, max_length=18),
        ),
    ]
