# Generated by Django 3.2.6 on 2021-09-05 20:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_auto_20210828_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=16, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username_lol',
            field=models.CharField(default=None, max_length=16, verbose_name='username_lol'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('jg', 'jg'), ('sup', 'sup'), ('top', 'top'), ('adc', 'adc')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('jg', 'jg'), ('sup', 'sup'), ('top', 'top'), ('adc', 'adc')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('jg', 'jg'), ('sup', 'sup'), ('top', 'top'), ('adc', 'adc')], default=None, max_length=18),
        ),
    ]
