# Generated by Django 3.2.6 on 2021-09-05 21:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20210905_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('jg', 'jg'), ('sup', 'sup'), ('adc', 'adc'), ('top', 'top')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('jg', 'jg'), ('sup', 'sup'), ('adc', 'adc'), ('top', 'top')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Masculino'), ('O', 'Outro'), ('F', 'Feminino')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('jg', 'jg'), ('sup', 'sup'), ('adc', 'adc'), ('top', 'top')], default=None, max_length=18),
        ),
    ]
