# Generated by Django 3.2.6 on 2021-09-06 19:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20210906_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'jg'), ('adc', 'adc'), ('top', 'top'), ('sup', 'sup'), ('mid', 'mid')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'jg'), ('adc', 'adc'), ('top', 'top'), ('sup', 'sup'), ('mid', 'mid')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'jg'), ('adc', 'adc'), ('top', 'top'), ('sup', 'sup'), ('mid', 'mid')], default=None, max_length=18),
        ),
    ]
