# Generated by Django 3.2.6 on 2021-09-09 14:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_auto_20210906_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='tutorial',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('top', 'top'), ('jg', 'jg'), ('sup', 'sup'), ('adc', 'adc')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('top', 'top'), ('jg', 'jg'), ('sup', 'sup'), ('adc', 'adc')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('O', 'Outro'), ('M', 'Masculino'), ('F', 'Feminino')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('top', 'top'), ('jg', 'jg'), ('sup', 'sup'), ('adc', 'adc')], default=None, max_length=18),
        ),
    ]
