# Generated by Django 3.2.6 on 2021-09-11 20:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20210909_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('sup', 'sup'), ('jg', 'jg'), ('top', 'top'), ('adc', 'adc')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('sup', 'sup'), ('jg', 'jg'), ('top', 'top'), ('adc', 'adc')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('F', 'Feminino'), ('O', 'Outro'), ('M', 'Masculino')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mid', 'mid'), ('sup', 'sup'), ('jg', 'jg'), ('top', 'top'), ('adc', 'adc')], default=None, max_length=18),
        ),
    ]
