# Generated by Django 3.2.6 on 2021-09-16 18:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20210911_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='duo_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sup', 'sup'), ('mid', 'mid'), ('top', 'top'), ('adc', 'adc'), ('jg', 'jg')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='first_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sup', 'sup'), ('mid', 'mid'), ('top', 'top'), ('adc', 'adc'), ('jg', 'jg')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='second_position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sup', 'sup'), ('mid', 'mid'), ('top', 'top'), ('adc', 'adc'), ('jg', 'jg')], default=None, max_length=18),
        ),
    ]
