# Generated by Django 3.2.6 on 2021-09-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210906_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
